- name: create project
  tower_project:
    name: "{{ proj_name }}"
    description: "{{ proj_desc }}"
    scm_url: "{{ scm_url }}"
    scm_branch: "{{ scm_branch }}"
    scm_update_on_launch: True
    scm_update_cache_timeout: 60
    custom_virtualenv: "/var/lib/awx/venv/ansible-2.2"
    state: present
    tower_config_file: "~/.tower_cli.cfg"
