- name: create project
  tower_project:
    organization: "{{ org_name }}"
    name: "{{ proj_name }}"
    description: "{{ proj_desc }}"
    scm_url: "{{ scm_url }}"
    scm_branch: "{{ scm_branch }}"
    scm_update_on_launch: True
    scm_update_cache_timeout: 60
    tower_host: "{{ tower_host_info }}"
    tower_username: "{{ tower_user_name }}"
    tower_password: "{{ tower_password }}"
    state: present
    tower_config_file: "{{ tower_cli_location }}"
