- name: Create Default Organization
  tower_organization:
    name: "{{ tower_credential_org }}"
    description: "{{ tower_org_description }}"
    state: "{{ tower_credential_state }}"
    tower_config_file: "{{ tower_cli_config }}"

- name: Create Homework Assignment project
# Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml
  command: |
    tower-cli project create -n "{{ proj_name }}" -d "{{ proj_desc }}" --organization "{{ org_name }}" --scm-type git --scm-url "{{ scm_url }}" --scm-branch "{{ scm_branch }}" -u "{{ tower_user_name }}" -p "{{ tower_password }}" -h "{{ tower_host_info }}" --wait

- name: Machine Credential (mispelled credential - tsk tsk) to connect to workstation using openstack.pub
  #command: |
    #tower-cli credential create -n "{{ tower_credential_name }}" --organization "{{ tower_credential_org }}" --credential-type "{{ tower_credential_type }}" -h "{{ tower_host_info }}" -u "{{ tower_user_name }}" -p "{{ tower_password }}" --inputs='{ "username": "{{ ssh_cred_name }}", "ssh_key_data": "{{ tower_credential_openstack_key }}" }'
  tower_credential:
    name: "{{ ssh_cred_name }}"
    organization: "{{ org_name }}"
    state: "{{ tower_credential_state }}"
    kind: ssh
    #tower_config_file: /root/.tower_cli.cfg
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    #tower_username: admin
    #tower_password: r3dh4t1!
    ssh_key_data: "{{ lookup('file', '{{ tower_credential_openstack_key }}') }}"
    user: "{{ user_cred_name }}"
    #username is for AWS.  Not clear if that's what's needed here
    #username: "{{ user_cred_name }}"

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}

- name: Add workstation host in tower_inventory
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"

- name: Associate workstation host to group
  command: |
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: admin
    tower_password: r3dh4t1!
    tower_verify_ssl: no
    ssh_key_data: "{{ lookup ('file', '~/.ssh/mykey.pem') }}"
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent
